import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";

const font = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio | Subham Mani",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased w-full max-w-screen-md mx-auto pb-10`}
      >
        {
          <ThemeProvider defaultTheme="light">
            <Navbar />
            {children}
            <Footer />
          </ThemeProvider>
        }
      </body>
    </html>
  );
}
